### ISSUE TITLE
LJ and Morse Bugs

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/EmpiricalPotentials.jl#26]
`iz1 || iz1` should be `iz1 || iz2`

**Comment by tjjarvinen** [comment]
There was also an additional bug where `eval_pair` did not return correct type.

The was triggered when forces where tried to calculate on a pair that had no entry in the potential.  In this case you want to return zero of `Dual` `r` not zero of `Float` `rcut`. This also had a type stability issue.
